//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication.WcfUser {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/ConnectionDb.classe")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfApplication.WcfUser.Client[] clientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mdpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string saltField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfApplication.WcfUser.Client[] client {
            get {
                return this.clientField;
            }
            set {
                if ((object.ReferenceEquals(this.clientField, value) != true)) {
                    this.clientField = value;
                    this.RaisePropertyChanged("client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mdp {
            get {
                return this.mdpField;
            }
            set {
                if ((object.ReferenceEquals(this.mdpField, value) != true)) {
                    this.mdpField = value;
                    this.RaisePropertyChanged("mdp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string salt {
            get {
                return this.saltField;
            }
            set {
                if ((object.ReferenceEquals(this.saltField, value) != true)) {
                    this.saltField = value;
                    this.RaisePropertyChanged("salt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://schemas.datacontract.org/2004/07/ConnectionDb.classe")]
    [System.SerializableAttribute()]
    public partial class Client : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numdossierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numtvaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfApplication.WcfUser.User[] userField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom {
            get {
                return this.nomField;
            }
            set {
                if ((object.ReferenceEquals(this.nomField, value) != true)) {
                    this.nomField = value;
                    this.RaisePropertyChanged("nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numdossier {
            get {
                return this.numdossierField;
            }
            set {
                if ((this.numdossierField.Equals(value) != true)) {
                    this.numdossierField = value;
                    this.RaisePropertyChanged("numdossier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numtva {
            get {
                return this.numtvaField;
            }
            set {
                if ((object.ReferenceEquals(this.numtvaField, value) != true)) {
                    this.numtvaField = value;
                    this.RaisePropertyChanged("numtva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfApplication.WcfUser.User[] user {
            get {
                return this.userField;
            }
            set {
                if ((object.ReferenceEquals(this.userField, value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://schemas.datacontract.org/2004/07/ConnectionDb.classe")]
    [System.SerializableAttribute()]
    public partial class Error : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int code {
            get {
                return this.codeField;
            }
            set {
                if ((this.codeField.Equals(value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfUser.WcfUser")]
    public interface WcfUser {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WcfUser/insert", ReplyAction="http://tempuri.org/WcfUser/insertResponse")]
        WpfApplication.WcfUser.Error insert(WpfApplication.WcfUser.User value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WcfUser/insert", ReplyAction="http://tempuri.org/WcfUser/insertResponse")]
        System.Threading.Tasks.Task<WpfApplication.WcfUser.Error> insertAsync(WpfApplication.WcfUser.User value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WcfUser/update", ReplyAction="http://tempuri.org/WcfUser/updateResponse")]
        WpfApplication.WcfUser.Error update(WpfApplication.WcfUser.User value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WcfUser/update", ReplyAction="http://tempuri.org/WcfUser/updateResponse")]
        System.Threading.Tasks.Task<WpfApplication.WcfUser.Error> updateAsync(WpfApplication.WcfUser.User value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WcfUser/delete", ReplyAction="http://tempuri.org/WcfUser/deleteResponse")]
        WpfApplication.WcfUser.Error delete(WpfApplication.WcfUser.User value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WcfUser/delete", ReplyAction="http://tempuri.org/WcfUser/deleteResponse")]
        System.Threading.Tasks.Task<WpfApplication.WcfUser.Error> deleteAsync(WpfApplication.WcfUser.User value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WcfUser/select", ReplyAction="http://tempuri.org/WcfUser/selectResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WpfApplication.WcfUser.User))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WpfApplication.WcfUser.Client[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WpfApplication.WcfUser.Client))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WpfApplication.WcfUser.User[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WpfApplication.WcfUser.Error))]
        WpfApplication.WcfUser.User[] select(object obj2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WcfUser/select", ReplyAction="http://tempuri.org/WcfUser/selectResponse")]
        System.Threading.Tasks.Task<WpfApplication.WcfUser.User[]> selectAsync(object obj2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WcfUserChannel : WpfApplication.WcfUser.WcfUser, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WcfUserClient : System.ServiceModel.ClientBase<WpfApplication.WcfUser.WcfUser>, WpfApplication.WcfUser.WcfUser {
        
        public WcfUserClient() {
        }
        
        public WcfUserClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WcfUserClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfUserClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfUserClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WpfApplication.WcfUser.Error insert(WpfApplication.WcfUser.User value) {
            return base.Channel.insert(value);
        }
        
        public System.Threading.Tasks.Task<WpfApplication.WcfUser.Error> insertAsync(WpfApplication.WcfUser.User value) {
            return base.Channel.insertAsync(value);
        }
        
        public WpfApplication.WcfUser.Error update(WpfApplication.WcfUser.User value) {
            return base.Channel.update(value);
        }
        
        public System.Threading.Tasks.Task<WpfApplication.WcfUser.Error> updateAsync(WpfApplication.WcfUser.User value) {
            return base.Channel.updateAsync(value);
        }
        
        public WpfApplication.WcfUser.Error delete(WpfApplication.WcfUser.User value) {
            return base.Channel.delete(value);
        }
        
        public System.Threading.Tasks.Task<WpfApplication.WcfUser.Error> deleteAsync(WpfApplication.WcfUser.User value) {
            return base.Channel.deleteAsync(value);
        }
        
        public WpfApplication.WcfUser.User[] select(object obj2) {
            return base.Channel.select(obj2);
        }
        
        public System.Threading.Tasks.Task<WpfApplication.WcfUser.User[]> selectAsync(object obj2) {
            return base.Channel.selectAsync(obj2);
        }
    }
}
