//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfAuthentification.bdd {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/ConnectionDb.classe")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfAuthentification.bdd.Client[] clientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mdpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string saltField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfAuthentification.bdd.Client[] client {
            get {
                return this.clientField;
            }
            set {
                if ((object.ReferenceEquals(this.clientField, value) != true)) {
                    this.clientField = value;
                    this.RaisePropertyChanged("client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mdp {
            get {
                return this.mdpField;
            }
            set {
                if ((object.ReferenceEquals(this.mdpField, value) != true)) {
                    this.mdpField = value;
                    this.RaisePropertyChanged("mdp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string salt {
            get {
                return this.saltField;
            }
            set {
                if ((object.ReferenceEquals(this.saltField, value) != true)) {
                    this.saltField = value;
                    this.RaisePropertyChanged("salt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://schemas.datacontract.org/2004/07/ConnectionDb.classe")]
    [System.SerializableAttribute()]
    public partial class Client : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numdossierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numtvaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfAuthentification.bdd.User[] userField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom {
            get {
                return this.nomField;
            }
            set {
                if ((object.ReferenceEquals(this.nomField, value) != true)) {
                    this.nomField = value;
                    this.RaisePropertyChanged("nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numdossier {
            get {
                return this.numdossierField;
            }
            set {
                if ((this.numdossierField.Equals(value) != true)) {
                    this.numdossierField = value;
                    this.RaisePropertyChanged("numdossier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numtva {
            get {
                return this.numtvaField;
            }
            set {
                if ((object.ReferenceEquals(this.numtvaField, value) != true)) {
                    this.numtvaField = value;
                    this.RaisePropertyChanged("numtva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfAuthentification.bdd.User[] user {
            get {
                return this.userField;
            }
            set {
                if ((object.ReferenceEquals(this.userField, value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transaction", Namespace="http://schemas.datacontract.org/2004/07/ConnectionDb.classe")]
    [System.SerializableAttribute()]
    public partial class Transaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfAuthentification.bdd.Transaction achatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfAuthentification.bdd.Client clientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double prixhtvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int tvaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string voitureField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfAuthentification.bdd.Transaction achat {
            get {
                return this.achatField;
            }
            set {
                if ((object.ReferenceEquals(this.achatField, value) != true)) {
                    this.achatField = value;
                    this.RaisePropertyChanged("achat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfAuthentification.bdd.Client client {
            get {
                return this.clientField;
            }
            set {
                if ((object.ReferenceEquals(this.clientField, value) != true)) {
                    this.clientField = value;
                    this.RaisePropertyChanged("client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double prixhtv {
            get {
                return this.prixhtvField;
            }
            set {
                if ((this.prixhtvField.Equals(value) != true)) {
                    this.prixhtvField = value;
                    this.RaisePropertyChanged("prixhtv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tva {
            get {
                return this.tvaField;
            }
            set {
                if ((this.tvaField.Equals(value) != true)) {
                    this.tvaField = value;
                    this.RaisePropertyChanged("tva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string voiture {
            get {
                return this.voitureField;
            }
            set {
                if ((object.ReferenceEquals(this.voitureField, value) != true)) {
                    this.voitureField = value;
                    this.RaisePropertyChanged("voiture");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://schemas.datacontract.org/2004/07/ConnectionDb.classe")]
    [System.SerializableAttribute()]
    public partial class Error : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int code {
            get {
                return this.codeField;
            }
            set {
                if ((this.codeField.Equals(value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="bdd.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/initialise", ReplyAction="http://tempuri.org/IService1/initialiseResponse")]
        bool initialise();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/initialise", ReplyAction="http://tempuri.org/IService1/initialiseResponse")]
        System.Threading.Tasks.Task<bool> initialiseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insert", ReplyAction="http://tempuri.org/IService1/insertResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfAuthentification.bdd.User))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfAuthentification.bdd.Client[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfAuthentification.bdd.Client))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfAuthentification.bdd.User[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfAuthentification.bdd.Transaction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfAuthentification.bdd.Error))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        WcfAuthentification.bdd.Error insert(object toto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insert", ReplyAction="http://tempuri.org/IService1/insertResponse")]
        System.Threading.Tasks.Task<WcfAuthentification.bdd.Error> insertAsync(object toto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/select", ReplyAction="http://tempuri.org/IService1/selectResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfAuthentification.bdd.User))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfAuthentification.bdd.Client[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfAuthentification.bdd.Client))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfAuthentification.bdd.User[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfAuthentification.bdd.Transaction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfAuthentification.bdd.Error))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        object[] select(object toto, object obj2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/select", ReplyAction="http://tempuri.org/IService1/selectResponse")]
        System.Threading.Tasks.Task<object[]> selectAsync(object toto, object obj2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/delete", ReplyAction="http://tempuri.org/IService1/deleteResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfAuthentification.bdd.User))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfAuthentification.bdd.Client[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfAuthentification.bdd.Client))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfAuthentification.bdd.User[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfAuthentification.bdd.Transaction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfAuthentification.bdd.Error))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        WcfAuthentification.bdd.Error delete(object toto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/delete", ReplyAction="http://tempuri.org/IService1/deleteResponse")]
        System.Threading.Tasks.Task<WcfAuthentification.bdd.Error> deleteAsync(object toto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/selectUser", ReplyAction="http://tempuri.org/IService1/selectUserResponse")]
        WcfAuthentification.bdd.User selectUser(WcfAuthentification.bdd.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/selectUser", ReplyAction="http://tempuri.org/IService1/selectUserResponse")]
        System.Threading.Tasks.Task<WcfAuthentification.bdd.User> selectUserAsync(WcfAuthentification.bdd.User user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WcfAuthentification.bdd.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WcfAuthentification.bdd.IService1>, WcfAuthentification.bdd.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public bool initialise() {
            return base.Channel.initialise();
        }
        
        public System.Threading.Tasks.Task<bool> initialiseAsync() {
            return base.Channel.initialiseAsync();
        }
        
        public WcfAuthentification.bdd.Error insert(object toto) {
            return base.Channel.insert(toto);
        }
        
        public System.Threading.Tasks.Task<WcfAuthentification.bdd.Error> insertAsync(object toto) {
            return base.Channel.insertAsync(toto);
        }
        
        public object[] select(object toto, object obj2) {
            return base.Channel.select(toto, obj2);
        }
        
        public System.Threading.Tasks.Task<object[]> selectAsync(object toto, object obj2) {
            return base.Channel.selectAsync(toto, obj2);
        }
        
        public WcfAuthentification.bdd.Error delete(object toto) {
            return base.Channel.delete(toto);
        }
        
        public System.Threading.Tasks.Task<WcfAuthentification.bdd.Error> deleteAsync(object toto) {
            return base.Channel.deleteAsync(toto);
        }
        
        public WcfAuthentification.bdd.User selectUser(WcfAuthentification.bdd.User user) {
            return base.Channel.selectUser(user);
        }
        
        public System.Threading.Tasks.Task<WcfAuthentification.bdd.User> selectUserAsync(WcfAuthentification.bdd.User user) {
            return base.Channel.selectUserAsync(user);
        }
    }
}
